CREATE TABLE `agent` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` tinyint(4) NOT NULL DEFAULT '0',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '区域级别：1-总部；2-全国；3-省级；4-市级；5-区县级；6-校级;',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT '代理商名称',
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `manager` varchar(20) NOT NULL DEFAULT '' COMMENT '负责人',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别：1-男；2-女',
  `id_number` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证号',
  `channel` tinyint(4) NOT NULL DEFAULT '0' COMMENT '来源渠道：0-其他;1-内部渠道；2-线上；3-线下；4-转介绍；',
  `introducer` varchar(20) NOT NULL DEFAULT '0' COMMENT '转介绍人姓名',
  `subagent_ownership` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否允许发展下级代理：0-不允许；1-允许',
  `subagent_level` varchar(20) NOT NULL DEFAULT '' COMMENT '发展下级代理商的级别：数字同level，数字之间用“,”分隔',
  `auth_limit` int(10) NOT NULL DEFAULT '0' COMMENT '授权额度（分）',
  `total_auth_limit` int(10) NOT NULL DEFAULT '0',
  `total_consume_limit` int(10) NOT NULL DEFAULT '0' COMMENT '累计消耗额度（分）',
  `total_in_join_fee` bigint(20) NOT NULL DEFAULT '0',
  `total_out_join_fee` bigint(20) NOT NULL DEFAULT '0',
  `total_in_prepay_fee` bigint(20) NOT NULL DEFAULT '0',
  `total_out_prepay_fee` bigint(20) NOT NULL DEFAULT '0',
  `auth_password` varchar(40) NOT NULL DEFAULT '' COMMENT '授权密码md5(加密)',
  `auth_salt` varchar(16) NOT NULL DEFAULT '' COMMENT '授权密码盐',
  `province` varchar(16) NOT NULL DEFAULT '' COMMENT '省',
  `city` varchar(20) NOT NULL DEFAULT '' COMMENT '市',
  `district` varchar(20) NOT NULL DEFAULT '' COMMENT '区县',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `supagent_id` int(10) NOT NULL DEFAULT '0' COMMENT '上级代理上id',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '父级链只是当前结点的父级，父级之间用“-”链接 -1-2-3-',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `join_start_at` date NOT NULL DEFAULT '0000-00-00' COMMENT '加盟开始时间',
  `join_end_at` date NOT NULL DEFAULT '0000-00-00' COMMENT '加盟到期时间',
  `operated_by` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='代理商表';

CREATE TABLE `agent_finance` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '代理商id',
  `other_agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '当发起收款的行为时，此处是agent_id下级代理商的id，当发起交款的行为时，此处是agent_id的上级代理商的id',
  `link_id` int(10) NOT NULL DEFAULT '0' COMMENT '链接id，当type是1，21的时候此处存agent_league表的id，当type=2，22的时候此处存agent_payment表的id',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型：1-交加盟费，2-交预付费,21-收加盟费，22-收预付款',
  `fee` int(10) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `operated_by` varchar(32) NOT NULL DEFAULT '' COMMENT ' 表示的是nickname字段，可修改',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='分销商收支记录表';

CREATE TABLE `agent_join` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `start_at` date NOT NULL DEFAULT '0000-00-00' COMMENT '加盟日期',
  `end_at` date NOT NULL DEFAULT '0000-00-00' COMMENT '加盟到期',
  `years` int(10) NOT NULL DEFAULT '0',
  `join_fee` int(10) NOT NULL DEFAULT '0' COMMENT '加盟费用（分）',
  `auth_limit` int(10) NOT NULL DEFAULT '0' COMMENT '授权额度（分）',
  `prepay_fee` int(10) NOT NULL DEFAULT '0' COMMENT '下级预付款（分）',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '交款代理商id',
  `supagent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属代理商id',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '父级链只是当前结点的父级，父级之间用“-”链接 -1-2-3-',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='加盟记录表';

CREATE TABLE `agent_limit_bill` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '代理商id',
  `other_agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '上级代理商或者下级代理商的id',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '分校ID',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型：1-给下级授权额度扣减；2-给下级加盟扣减；3-直营校发行课程卡扣减；21-上级增加授权额度',
  `fee` int(10) NOT NULL DEFAULT '0' COMMENT '额度：如果type是1，2，3则次字段是减，如果是type是21则次字段是增',
  `surplus` int(10) NOT NULL DEFAULT '0' COMMENT '剩余额度',
  `link_id` int(10) NOT NULL DEFAULT '0' COMMENT '链接id，当type是1，21的时候此处存agent_payment的id，是2的时候此处存agent_league的id，是3的时候此处存的是course_card_publish表的id',
  `reason` int(10) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `operated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '对应nickname字段',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='账户额度流水表';

CREATE TABLE `agent_prepay` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '交款代理商id',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '父级链只是当前结点的父级，父级之间用“-”链接 -1-2-3-',
  `supagent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属代理商id',
  `prepay_fee` int(10) NOT NULL DEFAULT '0' COMMENT '代理预付款',
  `auth_limit` int(10) NOT NULL DEFAULT '0' COMMENT '授权额度（分）',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='预付款记录表';

CREATE TABLE `agent_region` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `supagent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属代理商id',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '父级链',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '代理商id',
  `province` varchar(16) NOT NULL DEFAULT '' COMMENT '代理区域的省',
  `city` varchar(20) NOT NULL DEFAULT '' COMMENT '代理区域的市',
  `district` varchar(20) NOT NULL DEFAULT '' COMMENT '代理区域的县',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='代理商代理范围';

CREATE TABLE `agent_remark` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) unsigned NOT NULL DEFAULT '0',
  `link_id` int(10) unsigned NOT NULL DEFAULT '0',
  `type` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `remark` varchar(100) NOT NULL DEFAULT '',
  `reason` tinyint(4) NOT NULL DEFAULT '0',
  `operated_by` varchar(20) NOT NULL DEFAULT '',
  `updated_by` varchar(20) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `agent_role` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` varchar(300) NOT NULL DEFAULT '',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '分类：1-代理商角色；2-门店（分校）角色',
  `is_default` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1-内置角色，0-非内置',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '账号状态：0-正常；1-已下线（代理商不可分配此角色，不影响已有的，变相删除）',
  `actions` text NOT NULL COMMENT '角色权限,uri集合,多个uri用,分隔',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(20) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='代理商角色表';

CREATE TABLE `agent_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `nickname` varchar(20) NOT NULL DEFAULT '' COMMENT '姓名',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-正常;1-锁定;2-删除',
  `lock_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-没锁定；1-登陆次数过多锁定；2-人为锁定；3-加盟到期锁定',
  `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别：1-男；2-女',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `birthday` date NOT NULL DEFAULT '0000-00-00' COMMENT '出生日期',
  `password` varchar(40) NOT NULL DEFAULT '' COMMENT '密码',
  `salt` varchar(16) NOT NULL DEFAULT '' COMMENT '密码盐',
  `agent_id` int(10) NOT NULL DEFAULT '0',
  `privilege` tinyint(2) NOT NULL DEFAULT '0' COMMENT '特权：0-普通；1-上线验证期间可使用；2-系统维护中可以使用',
  `is_changed_password` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否重置过密码：0-没有；1-重置过',
  `last_login_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '上次登录时间',
  `sessionid` varchar(40) NOT NULL DEFAULT '' COMMENT '上次登录的session id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`) USING BTREE,
  KEY `mobile` (`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='人员表';

CREATE TABLE `agent_user_role` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) NOT NULL COMMENT 'agent_user的id',
  `agent_id` int(10) NOT NULL COMMENT '隶属代理商id',
  `store_id` int(10) NOT NULL COMMENT '隶属门店id',
  `role_ids` text NOT NULL COMMENT '角色id,多个id用,号分隔',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '账号类型（冗余字段）：1-代理商负责人；2-员工;3-教师；4-分校负责人',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `role` (`user_id`,`agent_id`,`store_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='人员角色对应关系表';

CREATE TABLE `app_active` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id号',
  `platform` varchar(16) NOT NULL DEFAULT '' COMMENT '平台:ios,android',
  `cid` varchar(64) NOT NULL DEFAULT '' COMMENT '激活id,App唯一',
  `version_no` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '版本号',
  `device_id` varchar(64) NOT NULL DEFAULT '' COMMENT '设备id,设备唯一',
  `source` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '安装渠道号',
  `ua` varchar(512) NOT NULL DEFAULT '' COMMENT 'UA信息',
  `ip` varchar(32) NOT NULL DEFAULT '' COMMENT '激活ip地址',
  `push_id` varchar(100) NOT NULL DEFAULT '' COMMENT '消息推送id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cid` (`cid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='App 激活信息表';

CREATE TABLE `app_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id号',
  `platform` varchar(16) NOT NULL DEFAULT '' COMMENT '平台:ios,android',
  `cid` varchar(64) NOT NULL DEFAULT '' COMMENT '激活id,App唯一',
  `version_no` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '版本号',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `mobile` varchar(16) NOT NULL DEFAULT '' COMMENT '反馈用户手机号',
  `message` text NOT NULL COMMENT 'crash记录',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='App日志记录表';

CREATE TABLE `app_publish` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id号',
  `platform` varchar(16) NOT NULL DEFAULT '' COMMENT '平台:ios,android',
  `package_url` varchar(255) NOT NULL DEFAULT '' COMMENT '软件下载地址',
  `page_url` varchar(255) NOT NULL DEFAULT '' COMMENT '下载页面地址',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(16) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `version` (`pid`,`platform`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='App发布信息';

CREATE TABLE `app_suggest` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(10) NOT NULL DEFAULT '0' COMMENT '登陆用户id',
  `mobile` varchar(16) NOT NULL DEFAULT '' COMMENT '反馈用户手机号',
  `content` varchar(500) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '反馈内容',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '反馈类型',
  `image_ids` varchar(200) NOT NULL DEFAULT '' COMMENT '反馈图片pid，多张用英文逗号分隔',
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id号',
  `phone_model` varchar(28) NOT NULL DEFAULT '' COMMENT '手机型号',
  `os_version` varchar(16) NOT NULL DEFAULT '' COMMENT '操作系统版本',
  `network` varchar(10) NOT NULL DEFAULT '' COMMENT '网络类型',
  `platform` varchar(16) NOT NULL DEFAULT '' COMMENT '平台:ios,android',
  `cid` varchar(64) NOT NULL DEFAULT '' COMMENT 'App 激活id',
  `version_no` int(10) NOT NULL DEFAULT '0' COMMENT 'App 版本号',
  `ip` varchar(32) NOT NULL DEFAULT '' COMMENT '反馈者ip',
  `sign` varchar(32) NOT NULL DEFAULT '' COMMENT '数据签名,防止重复提交',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
  PRIMARY KEY (`id`),
  KEY `cid` (`cid`) USING BTREE,
  KEY `app` (`pid`,`platform`,`version_no`) USING BTREE,
  KEY `sign` (`sign`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='App 意见反馈表';

CREATE TABLE `app_version` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id号',
  `no` int(10) NOT NULL DEFAULT '0' COMMENT '版本号',
  `platform` varchar(16) NOT NULL DEFAULT '' COMMENT '平台:ios,android',
  `title` varchar(64) NOT NULL DEFAULT '' COMMENT '升级提示标题',
  `description` text NOT NULL COMMENT '升级信息,用|||表示换行符',
  `url` varchar(255) NOT NULL DEFAULT '' COMMENT '软件升级地址',
  `version` varchar(32) NOT NULL DEFAULT '' COMMENT '版本信息,eq:v1.0.1',
  `status` varchar(4) NOT NULL DEFAULT '' COMMENT 'N:最新版本;O:不提示升级;A:提示升级;E强制升级;',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(16) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  KEY `version` (`pid`,`platform`,`no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='App 版本信息表';

CREATE TABLE `card_produce` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '课程卡名字',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '卡类型：1-体验卡；2-同步教材卡；3-综合课程卡',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店ID',
  `product_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '产品类型：1-单词卡，2-...',
  `create_num` int(10) NOT NULL DEFAULT '0' COMMENT '生成数量',
  `publish_num` int(10) NOT NULL DEFAULT '0' COMMENT '发行数量',
  `activate_num` int(10) NOT NULL DEFAULT '0' COMMENT '激活数量',
  `fee` int(10) NOT NULL DEFAULT '0' COMMENT '生成这批卡的发行后的费用（分）',
  `unit_fee` int(10) NOT NULL DEFAULT '0' COMMENT '生成卡的时候的卡的单价（分）',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属上级ID',
  `start_sn` varchar(20) NOT NULL DEFAULT '' COMMENT '课程卡开始编号',
  `end_sn` varchar(20) NOT NULL DEFAULT '' COMMENT '课程卡结束编号',
  `publish_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '发行时间',
  `scope_type` tinyint(4) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '生成人',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='课程卡表';

CREATE TABLE `card_publish` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `fee` int(10) NOT NULL DEFAULT '0' COMMENT '发行消耗的钱',
  `card_word_ids` text NOT NULL COMMENT '本次发行的卡的卡id，英文逗号做分隔',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店ID',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属上级ID',
  `personnel_id` int(10) NOT NULL DEFAULT '0' COMMENT '发行卡人id',
  `card_name` varchar(500) NOT NULL DEFAULT '' COMMENT '此次发行卡名字,用逗号分隔'',''',
  `card_type` varchar(20) NOT NULL DEFAULT '' COMMENT '此次发行课程卡类型，用'',''分隔',
  `scope_type` varchar(100) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='课程卡发行记录表';

CREATE TABLE `card_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店ID',
  `personnel_id` int(10) NOT NULL DEFAULT '0' COMMENT '发行人id',
  `active_wordset_id` varchar(50) NOT NULL DEFAULT '' COMMENT '词库ID',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '课程卡激活状态：1-未激活，2-已激活，3-已过期，4-已失效',
  `use_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '使用状态：1-未使用；2-已使用',
  `publish_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '发行状态：1-未发行，2-已发行',
  `valid_days` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '有效期天数',
  `experience_num` int(10) NOT NULL DEFAULT '0' COMMENT '体验次数',
  `student_wordset_id` varchar(50) NOT NULL DEFAULT '' COMMENT '学生词库ids(体验卡可以激活多个)，用短线分隔，为了查询-2-3-',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '课程卡类型：1-单册；2-多册；',
  `scope_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '课程卡范围类型：1-普通体验卡；2-vip体验卡；3-小学同步教材；4-初中同步教材；5-高中同步教材；6-小学考纲；7-中考考纲；8-高考考纲；9-四级课程；10-六级课程；11-托福课程；12-雅思课程',
  `wordset_ids` text NOT NULL COMMENT '所涉及到的课程卡，如果有全部词库，则为''全部''',
  `card_produce_id` int(10) NOT NULL DEFAULT '0' COMMENT '主课程卡表id',
  `sn` varchar(20) NOT NULL DEFAULT '' COMMENT '课程卡编号',
  `plaintext` varchar(255) NOT NULL DEFAULT '' COMMENT '明文密码（体验卡才有）',
  `secret_key` varchar(32) NOT NULL DEFAULT '' COMMENT '卡密（卡号+密码md5加密）',
  `id_equal_value` varchar(10) NOT NULL DEFAULT '' COMMENT 'id对应的34位进制数',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属上级ID',
  `cid` varchar(64) NOT NULL DEFAULT '' COMMENT '激活id,App唯一',
  `province` varchar(16) NOT NULL DEFAULT '' COMMENT '激活时的省',
  `city` varchar(20) NOT NULL DEFAULT '' COMMENT '激活时的市',
  `district` varchar(20) NOT NULL DEFAULT '' COMMENT '激活时的区县',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '激活时的具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '维度',
  `ip` varchar(32) NOT NULL DEFAULT '' COMMENT '激活课程卡ip地址',
  `active_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '卡的激活时间',
  `expire_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '过期时间',
  `publish_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '发行时间',
  `cancel_activated_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `reset_identify` int(8) NOT NULL DEFAULT '0',
  `fee` int(10) NOT NULL DEFAULT '0',
  `cancel_fee` int(10) NOT NULL DEFAULT '0',
  `activate_type` tinyint(4) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `activated_by` varchar(32) NOT NULL DEFAULT '',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `operated_by` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `sn` (`sn`) USING BTREE,
  UNIQUE KEY `id_equal_value` (`id_equal_value`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单词课程卡表';

CREATE TABLE `classes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `is_default` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是不是默认班级：1-是；0-否',
  `name` varchar(40) NOT NULL DEFAULT '' COMMENT '班级名字',
  `password` varchar(40) NOT NULL DEFAULT '' COMMENT '班级密码',
  `teacher_user_id` int(10) NOT NULL DEFAULT '0' COMMENT '教师id',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态：1-未结课；2-已结课',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  KEY `password` (`password`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='班级表';

CREATE TABLE `coin_exchange` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL DEFAULT '0' COMMENT '学生ID',
  `coin_goods_id` int(11) NOT NULL DEFAULT '0' COMMENT '商品ID',
  `class_id` int(11) NOT NULL DEFAULT '0' COMMENT '班级ID',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '兑换个数',
  `coin` int(11) NOT NULL DEFAULT '0' COMMENT '消耗的金币数',
  `total_coin` int(11) NOT NULL DEFAULT '0' COMMENT '剩余金币数',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `operated_by` varchar(255) NOT NULL DEFAULT '' COMMENT '操作人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='兑换表';

CREATE TABLE `coin_goods` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
  `coin` int(11) NOT NULL DEFAULT '0' COMMENT '兑换金币数',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '兑换人数',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1-正常；2-下架',
  `created_by` varchar(255) NOT NULL COMMENT '创建者',
  `updated_by` varchar(255) NOT NULL COMMENT '更新者',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表';

CREATE TABLE `event_message` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event` varchar(50) NOT NULL COMMENT '事件',
  `args` longtext NOT NULL COMMENT '事件参数',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='事件消息表';

CREATE TABLE `mnemonic` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `content` text NOT NULL COMMENT '助记内容',
  `format` tinyint(4) NOT NULL DEFAULT '0' COMMENT '助记格式：1--富文本  2--图片url  3--声音url  4--视频url',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '助记类型:0-其它;1-联想;2-谐音;3-词根;4-扩展;5-串记;6-口诀;7-对比;8-语法;9-词源;10-分析;11-合成',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '级别，1-小学,2-初中，3-高中，4-大学，5-大学以上',
  `solomon_id` int(10) NOT NULL DEFAULT '0' COMMENT 'solomon数据库中的表id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `updated_by` varchar(20) NOT NULL DEFAULT '' COMMENT '最后修改者',
  `source` tinyint(4) NOT NULL DEFAULT '0' COMMENT '来源\r\n0 未处理\r\n1 钱磊\r\n2 自编\r\n100 不详',
  `word_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '单词id，逗号分割',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='英语单词助记信息表';

CREATE TABLE `resource_version` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `version_no` int(10) NOT NULL DEFAULT '0',
  `description` text NOT NULL,
  `word_block_url` varchar(255) NOT NULL DEFAULT '',
  `last_txt_url` varchar(255) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(16) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `store` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '代理商id',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '代理商父级链只是当前结点的父级，父级之间用“-”链接 1-2-3,包含自己的代理商',
  `sn` varchar(9) NOT NULL DEFAULT '' COMMENT '分校的编号',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT '门店名称',
  `province` varchar(16) NOT NULL DEFAULT '' COMMENT '省',
  `city` varchar(20) NOT NULL DEFAULT '' COMMENT '市',
  `district` varchar(20) NOT NULL DEFAULT '' COMMENT '区县',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL COMMENT '经度',
  `latitude` varchar(16) NOT NULL COMMENT '维度',
  `experience_card_num` int(10) NOT NULL DEFAULT '0' COMMENT '体验卡激活数量',
  `material_card_num` int(10) NOT NULL DEFAULT '0' COMMENT '教材卡激活数量',
  `comprehensive_card_num` int(10) NOT NULL DEFAULT '0' COMMENT '综合卡数量',
  `operated_by` varchar(32) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `sn` (`sn`) USING BTREE,
  UNIQUE KEY `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='门店信息表';

CREATE TABLE `student` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sn` varchar(15) NOT NULL DEFAULT '' COMMENT '学生的编号',
  `teacher_user_id` int(10) NOT NULL DEFAULT '0' COMMENT '教师id',
  `class_id` int(10) NOT NULL DEFAULT '0' COMMENT '班级id',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店id',
  `agent_id` int(10) NOT NULL DEFAULT '0' COMMENT '直属代理商id',
  `pad_mode` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'PAD端学习模式：0-未设置；1-智能学习；2-点读学习',
  `phone_mode` tinyint(4) NOT NULL DEFAULT '1' COMMENT '手机端学习模式：0-未设置；1-智能学习；2-点读学习',
  `supagent_chain` varchar(50) NOT NULL DEFAULT '' COMMENT '代理商父级链只是当前结点的父级，父级之间用“-”链接 1-2-3,包含自己的代理商',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型：1-开始体验；2-体验到期；3-在读；4-课程过期',
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '姓名',
  `username` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `session_id` varchar(48) NOT NULL DEFAULT '' COMMENT '用户pad端session_id',
  `password` varchar(40) NOT NULL DEFAULT '' COMMENT '登录密码',
  `coin` int(10) NOT NULL DEFAULT '0' COMMENT '学豆数',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `salt` varchar(16) NOT NULL DEFAULT '' COMMENT '密码盐',
  `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别：1-男；2-女',
  `stage` tinyint(4) NOT NULL DEFAULT '0' COMMENT '学段：1-小学；2-初中；3-高中',
  `grade` varchar(4) NOT NULL DEFAULT '' COMMENT '年级:三年级',
  `school` varchar(50) NOT NULL DEFAULT '' COMMENT '就读学校',
  `sound_type` tinyint(4) NOT NULL DEFAULT '2' COMMENT '学生设置发音音标类型：1-美音；2-英音',
  `last_test_level` int(20) NOT NULL DEFAULT '0' COMMENT '上一次词汇量检测等级',
  `birthday` date NOT NULL DEFAULT '0000-00-00' COMMENT '生日',
  `last_study_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后学习时间',
  `wordset_activate_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近一次激活非体验课程卡时间',
  `experience_activate_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近一次激活体验课程的时间',
  `experience_expire_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '体验到期日期',
  `wordset_expire_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '课程到期日期',
  `left_experience_num` int(10) NOT NULL DEFAULT '0' COMMENT '剩余体验次数',
  `total_experience_days` int(10) NOT NULL DEFAULT '0' COMMENT '总共可以体验的天数',
  `total_experience_num` int(10) NOT NULL DEFAULT '0' COMMENT '总共可以体验次数',
  `source` tinyint(4) NOT NULL DEFAULT '0' COMMENT '来源：1-进校；2-到店咨询；3-线上咨询；4-转介绍；5-其他',
  `introducer` varchar(20) NOT NULL DEFAULT '' COMMENT '介绍人姓名',
  `qq` varchar(20) NOT NULL DEFAULT '' COMMENT 'QQ号',
  `condition` varchar(500) NOT NULL DEFAULT '' COMMENT '学员情况',
  `province` varchar(16) NOT NULL DEFAULT '' COMMENT '首次激活的省',
  `city` varchar(20) NOT NULL DEFAULT '' COMMENT '首次激活的市',
  `district` varchar(20) NOT NULL DEFAULT '' COMMENT '首次激活的区县',
  `address` varchar(500) NOT NULL DEFAULT '' COMMENT '首次激活的详细地址',
  `parents` text NOT NULL COMMENT '家长信息：json格式[{"name":"姓名","mobile":"手机号","relationship":"亲属关系"}]',
  `register_province` varchar(16) NOT NULL DEFAULT '' COMMENT '注册省',
  `register_city` varchar(20) NOT NULL DEFAULT '' COMMENT '注册市',
  `register_district` varchar(20) NOT NULL DEFAULT '' COMMENT '注册区',
  `register_address` varchar(500) NOT NULL DEFAULT '' COMMENT '注册地址',
  `register_longitude` varchar(16) NOT NULL COMMENT '经度',
  `register_latitude` varchar(16) NOT NULL COMMENT '维度',
  `is_attention` tinyint(4) NOT NULL DEFAULT '0',
  `last_student_unit_id` int(10) NOT NULL DEFAULT '0',
  `shorthand_duration` int(10) NOT NULL DEFAULT '0' COMMENT '学生学习时长（排除当天）',
  `total_duration` int(10) NOT NULL DEFAULT '0' COMMENT '总学习时长（排除当天）',
  `study_new_word` int(10) NOT NULL DEFAULT '0' COMMENT '学习新单词数(排除当天)',
  `reviewed_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '复习单词总数(排除当天)',
  `reviewed_duration` int(10) NOT NULL DEFAULT '0' COMMENT '复习总时长(排除当天)',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `sn` (`sn`) USING BTREE,
  KEY `mobile` (`mobile`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生信息表';

CREATE TABLE `student_coin_bill` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL DEFAULT '0' COMMENT '学生ID',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型：1-智能学习；2-词义闯关；3-听写；4-默写；5-复习；6-点读学习',
  `study_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '学习时间',
  `link_id` text NOT NULL COMMENT '关联表ID，都是大表，对于复习的话是这次复习的所有ID',
  `detail` text NOT NULL COMMENT '详细记录，记录一些必要信息',
  `coin` int(11) NOT NULL DEFAULT '0' COMMENT '本次获得的金币',
  `total_coin` int(11) NOT NULL DEFAULT '0' COMMENT '总的金币',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(16) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='金币对账表';

CREATE TABLE `student_review_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1-答对；2-答错;',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '复习时长（毫秒）',
  `intensify_review_right_num` int(10) NOT NULL DEFAULT '0' COMMENT '强化阶段正确次数',
  `intensify_review_wrong_num` int(11) NOT NULL DEFAULT '0' COMMENT '强化阶段错误次数',
  `composite_spell_wrong_num` int(11) NOT NULL DEFAULT '0' COMMENT '组合拼写错误次数',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL COMMENT '经度',
  `latitude` varchar(16) NOT NULL COMMENT '维度',
  `current_start_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '本次复习的开始时间，代表一次复习的开始时间',
  `should_review_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '单词本该复习的时间',
  `start_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '复习开始时间',
  `end_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '复习结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_id` (`student_id`) USING BTREE,
  KEY `student_id_current_start_at` (`student_id`,`current_start_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生已复习表';

CREATE TABLE `student_study_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `store_id` int(10) NOT NULL DEFAULT '0',
  `agent_id` int(10) NOT NULL DEFAULT '0',
  `student_id` int(10) NOT NULL DEFAULT '0',
  `study_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `wordset_id` int(10) NOT NULL DEFAULT '0',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0',
  `unit_no` int(10) NOT NULL DEFAULT '0',
  `type` tinyint(4) NOT NULL DEFAULT '0',
  `content` varchar(200) NOT NULL DEFAULT '',
  `duration` int(10) NOT NULL DEFAULT '0',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '每次获得的学分',
  `link_id` text NOT NULL COMMENT '每次获取学分的途径，多个用’,‘分隔,1、6-unit_shorthand_word_id,2-unit_check_id,3-unit_dictate_id,4-unit_write_id,5-student_review_word_id',
  `detail` text NOT NULL COMMENT '详细记录，记录一些必要信息',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `student_id` (`student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `student_testing` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '记录id',
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `cid` varchar(64) NOT NULL DEFAULT '' COMMENT 'cid',
  `type` tinyint(10) NOT NULL DEFAULT '0' COMMENT ' 测评类型:0-看图知心里;1-天赋领域 测评;2-情商测评;3-学习动机;4-意志力;5-成就动机;6-环境评价;7-观察力测评;8-记忆力测评;9-思维力评测;10-想象力评测;11-注意力评测;12-个性倾向评测;13-感知模式测评;14色彩性格测评;15考试焦虑测评;16家长PEM测评;17-未来成功人士;18-未来学历;19-文理科;20-未来职业;21-学习压力指数;22-自信心;23-人际关系困扰指数;',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '总耗时（秒）',
  `answer` varchar(500) NOT NULL DEFAULT '' COMMENT '答案，多个答案用英文逗号分隔',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_id` (`student_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生学习测评表';

CREATE TABLE `student_unit` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1-未学习；2-学习中；3-学完未测；4-已测试未通过；5-已测通过',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '总单词数',
  `shorthand_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记次数',
  `study_num` int(10) NOT NULL DEFAULT '0',
  `check_num` int(10) NOT NULL DEFAULT '0' COMMENT '检查次数',
  `dictate_num` int(10) NOT NULL DEFAULT '0',
  `write_num` int(10) NOT NULL DEFAULT '0',
  `last_unit_check_id` int(10) NOT NULL DEFAULT '0',
  `last_check_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '最近一次检查正确单词数',
  `highest_check_accuracy` int(10) NOT NULL DEFAULT '0' COMMENT '本单元正确率最高历史纪录',
  `first_check_accuracy` int(10) NOT NULL DEFAULT '0' COMMENT '首次检查正确率',
  `last_check_accuracy` int(10) NOT NULL DEFAULT '0' COMMENT '最近一次检查正确率',
  `last_check_accuracy_increment` int(10) NOT NULL DEFAULT '0' COMMENT '正确率增量(-5表示下降5%,5表示上升5%,0表示无增量)',
  `last_check_duration` int(10) NOT NULL DEFAULT '0' COMMENT '最近一次检查时长（秒）',
  `last_check_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近一次检查时间',
  `last_unit_dictate_id` int(10) NOT NULL DEFAULT '0',
  `last_dictate_correct_num` int(10) NOT NULL DEFAULT '0',
  `highest_dictate_accuracy` int(10) NOT NULL DEFAULT '0',
  `first_dictate_accuracy` int(10) NOT NULL DEFAULT '0',
  `last_dictate_accuracy` int(10) NOT NULL DEFAULT '0',
  `last_dictate_accuracy_increment` int(10) NOT NULL DEFAULT '0',
  `last_dictate_duration` int(10) NOT NULL DEFAULT '0',
  `last_dictate_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `last_unit_memory_write_id` int(10) NOT NULL DEFAULT '0',
  `last_write_correct_num` int(10) NOT NULL DEFAULT '0',
  `highest_write_accuracy` int(10) NOT NULL DEFAULT '0',
  `first_write_accuracy` int(10) NOT NULL DEFAULT '0',
  `last_write_accuracy` int(10) NOT NULL DEFAULT '0',
  `last_write_accuracy_increment` int(10) NOT NULL DEFAULT '0',
  `last_write_duration` int(10) NOT NULL DEFAULT '0',
  `last_write_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_wordset_id` (`student_wordset_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生单元表';

CREATE TABLE `student_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元表id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `word_id` varchar(200) NOT NULL DEFAULT '' COMMENT '单词id',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `wordset_word_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库表单词id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `group_no` int(10) NOT NULL DEFAULT '0' COMMENT '组号',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生已购单词表(一个单元一个单元的插入)';

CREATE TABLE `student_word_statistics` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础单词id',
  `word_difficulty` double NOT NULL DEFAULT '0' COMMENT '单词的记忆难度λ',
  `word_review_frequency` double NOT NULL DEFAULT '0' COMMENT '单词的遗忘指数β，如果单词是熟记的话该值是0.1，否则根据算法算出来',
  `highest_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '最高级别词库id',
  `last_unit_no` int(10) NOT NULL DEFAULT '0',
  `wordset_word_id` int(10) NOT NULL DEFAULT '0',
  `wordset_stage` tinyint(4) NOT NULL DEFAULT '0' COMMENT '最高级别词库学段：1-小学；2-初中；3-高中；4-大学',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词类型：1-生词；2-熟词；3-夹生词',
  `review_num` int(10) NOT NULL DEFAULT '0' COMMENT '复习次数',
  `review_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '复习正确次数',
  `review_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '复习错误次数',
  `shorthand_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记次数',
  `shorthand_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记正确次数',
  `shorthand_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记错误次数',
  `check_num` int(10) NOT NULL DEFAULT '0' COMMENT '检查次数',
  `check_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '检查正确次数',
  `check_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '检查错误次数',
  `last_check_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '最后一次检查状态：1-正确；2-错误',
  `dictate_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写正确次数',
  `dictate_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写错误次数',
  `memory_write_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写错误次数',
  `memory_write_correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写正确次数',
  `correct_num` int(10) NOT NULL DEFAULT '0' COMMENT '总正确次数',
  `wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '总错误次数',
  `review_days` int(10) NOT NULL DEFAULT '0' COMMENT '复习的天数，每次重新识记会重置',
  `last_shorthand_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近一次识记时间',
  `last_review_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近一次复习时间',
  `next_review_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '下一次正常复习时间',
  `check_pure_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '检查纯错误次数：错误次数-正确次数',
  `last_wrong_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最新错误时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_word` (`student_id`,`word_id`),
  KEY `student_id` (`student_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生单词统计表';

CREATE TABLE `student_wordset` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `store_id` int(10) NOT NULL DEFAULT '0' COMMENT '门店id',
  `course_card_id` int(10) NOT NULL DEFAULT '0' COMMENT '绑定最新课程卡记录id（card_word表的id）',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态：1-未激活；2-已激活；3-激活已过期；4-未激活已过期(课程未激活的过期)',
  `valid_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '生效时间',
  `invalid_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '失效时间',
  `cancel_activate_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `study_unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '已学习单元数',
  `study_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '已学习单词数',
  `dictate_unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写单元数',
  `dictate_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写单词数',
  `write_unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写单元数',
  `write_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写单词数',
  `total_unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '单元总数',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '课程总单词数',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `operated_by` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_wordset` (`student_id`,`wordset_id`) USING BTREE COMMENT '学生词库联合索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生词库表';

CREATE TABLE `study_day_report` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `shorthand_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记生词单词数',
  `shorthand_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '识记单词数',
  `shorthand_duration` int(10) NOT NULL DEFAULT '0' COMMENT '识记时长：秒',
  `dictate_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写单词数',
  `dictate_wrong_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写单词错误数',
  `dictate_duration` int(10) NOT NULL DEFAULT '0' COMMENT '听写时长：秒',
  `write_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写单词数',
  `write_wrong_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写单词错误数',
  `write_duration` int(10) NOT NULL DEFAULT '0' COMMENT '默写时长：秒',
  `reviewed_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '已复习单词数',
  `reviewed_wrong_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '已复习单词错误数',
  `reviewed_duration` int(10) NOT NULL DEFAULT '0' COMMENT '复习时长：秒',
  `not_reviewed_num` int(10) NOT NULL DEFAULT '0' COMMENT '今天没有复习的单词数',
  `study_new_word` int(10) NOT NULL DEFAULT '0',
  `date` date NOT NULL DEFAULT '0000-00-00' COMMENT '日期',
  `coin` int(10) NOT NULL DEFAULT '0',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `check_word_num` int(10) NOT NULL DEFAULT '0',
  `check_wrong_word_num` int(10) NOT NULL DEFAULT '0',
  `check_duration` int(10) NOT NULL DEFAULT '0',
  `shorthand_familiar_num` int(10) NOT NULL DEFAULT '0',
  `shorthand_rawish_num` int(10) NOT NULL DEFAULT '0',
  `check_score` text NOT NULL,
  `dictate_score` text NOT NULL,
  `write_score` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `student_id` (`student_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='每日学习情况';

CREATE TABLE `sys_admin` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `nickname` varchar(16) NOT NULL DEFAULT '' COMMENT '昵称',
  `password` varchar(40) NOT NULL DEFAULT '' COMMENT '密码',
  `mobile` varchar(16) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0-正常;1-锁定;2-删除',
  `privilege` tinyint(2) NOT NULL DEFAULT '0' COMMENT '特权：0-普通；1-上线验证期间可使用；2-系统维护中可以使用',
  `role_ids` text NOT NULL COMMENT '角色id,多个id用,号分隔',
  `salt` varchar(16) NOT NULL DEFAULT '' COMMENT '密码盐',
  `sessionid` varchar(40) NOT NULL DEFAULT '' COMMENT '上次登录的session id',
  `last_login_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '上次登录时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`) USING BTREE,
  UNIQUE KEY `mobile` (`mobile`) USING BTREE,
  KEY `status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='系统管理员用户表';

CREATE TABLE `sys_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '管理员用户名',
  `action` varchar(200) NOT NULL DEFAULT '' COMMENT '操作uri',
  `body` text NOT NULL COMMENT '请求参数',
  `ip` varchar(16) NOT NULL DEFAULT '' COMMENT '操作者IP',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `uname` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='系统用户操作日志表';

CREATE TABLE `sys_role` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` varchar(300) NOT NULL DEFAULT '',
  `actions` text NOT NULL COMMENT '角色权限,uri集合,多个uri用,分隔',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(20) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='系统角色表';

CREATE TABLE `teacher` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) NOT NULL COMMENT 'agent_user的id',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型：1-全职；2-兼职',
  `school` varchar(50) NOT NULL DEFAULT '' COMMENT '院校',
  `en_level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '英语等级：1-高中； 2- 四级； 3-六级； 4-专四以上',
  `is_certificate` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否有教师资格证：0-无，1-有',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `education` tinyint(4) NOT NULL DEFAULT '0' COMMENT '学历：1-高中及以下、2-专科、3-本科、4-研究生、5-博士',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='教师表';

CREATE TABLE `timing_task` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `event` varchar(50) NOT NULL COMMENT '事件',
  `args` text NOT NULL COMMENT '定时任务参数',
  `execute_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='定时任务表';

CREATE TABLE `unit_check` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `wordset_id` int(11) NOT NULL DEFAULT '0' COMMENT '词库id',
  `coin` int(10) NOT NULL DEFAULT '0' COMMENT '金币数',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '总单词数',
  `correct_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '正确单词数',
  `score` int(10) NOT NULL DEFAULT '0',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '维度',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '检查时长（秒）',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_wordset_id` (`student_wordset_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单元检测表';

CREATE TABLE `unit_check_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_check_id` int(10) NOT NULL DEFAULT '0' COMMENT '检测单元id',
  `wordset_id` int(11) NOT NULL DEFAULT '0' COMMENT '词库id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `answer_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '回答类型：1-答对；2-答错；3-不认识此单词',
  `is_answer_overtime` tinyint(4) NOT NULL DEFAULT '0' COMMENT '回答是否超时：0-没有超时；1-超时',
  `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '检测方式：1-看英文选中文；2-听力选择；3-组合拼；4-全拼',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '检测时长（毫秒）',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生单元检测单词表';

CREATE TABLE `unit_dictate` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `coin` int(10) NOT NULL DEFAULT '0' COMMENT '金币数',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `right_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写答对正确的单词数',
  `actual_num` int(11) NOT NULL DEFAULT '0',
  `wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '听写错误的单词数',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '单词总数',
  `score` int(10) NOT NULL DEFAULT '0',
  `is_completed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否完成：0-未完成；1-已完成',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '单词听写时长（秒）',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单元听写记录表';

CREATE TABLE `unit_dictate_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_dictate_id` int(10) NOT NULL DEFAULT '0' COMMENT '检测单元id',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `answer_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '回答类型：1-首次答对；2-错误',
  `wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '错误次数',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '检测时长（毫秒）',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '听写开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '听写结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生单元检测单词表';

CREATE TABLE `unit_memory_write` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `wordset_id` int(11) NOT NULL DEFAULT '0' COMMENT '词库id',
  `coin` int(10) NOT NULL DEFAULT '0' COMMENT '金币数',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `right_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写正确的单词数',
  `actual_num` int(11) NOT NULL DEFAULT '0',
  `wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '默写错误的单词数',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '单词总数',
  `score` int(10) NOT NULL DEFAULT '0',
  `is_completed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否完成：0-未完成；1-已完成',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '单词默写时长（秒）',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单元智能默写记录表';

CREATE TABLE `unit_memory_write_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '单词ID',
  `wordset_id` int(11) NOT NULL DEFAULT '0' COMMENT '词库id',
  `unit_memory_write_id` int(10) NOT NULL DEFAULT '0' COMMENT '单元智能默写记录表id',
  `answer_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '回答类型：1-首次答对；2-答错',
  `wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '错误单词数',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '单词默写时长（毫秒）',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `type` int(10) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单元智能默写记录单词表';

CREATE TABLE `unit_shorthand` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生单元id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `coin` int(10) NOT NULL DEFAULT '0' COMMENT '金币数',
  `credit` int(10) NOT NULL DEFAULT '0' COMMENT '学分',
  `is_completed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否完成：0-未完成；1-已完成',
  `study_group_no` int(10) NOT NULL DEFAULT '0' COMMENT '学习进度：学习中途退出则插入当前组数，学习完成则置0',
  `click_study_group_no` int(10) NOT NULL DEFAULT '0' COMMENT '点读学习到哪组，学完置成0',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `duration` int(11) NOT NULL DEFAULT '0' COMMENT '学习总时长(秒)',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记结束时间',
  `is_click_choose` tinyint(4) NOT NULL DEFAULT '0' COMMENT '点读模式是否选择生词熟词：0-没选过；1-选过',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_wordset_id` (`student_wordset_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生识记记录表';

CREATE TABLE `unit_shorthand_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生id',
  `student_wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '学生词库id',
  `student_unit_id` int(10) NOT NULL DEFAULT '0' COMMENT '识记单元id',
  `unit_shorthand_id` int(10) NOT NULL DEFAULT '0' COMMENT '识记id',
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词类型：1-生词；2-熟词；3-夹生词',
  `is_completed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否完成：0-未完成；1-已完成',
  `group_no` int(10) NOT NULL DEFAULT '0' COMMENT '组号',
  `read_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '拼读错误次数',
  `read_right_num` int(11) NOT NULL DEFAULT '0' COMMENT '拼读正确次数',
  `composite_spell_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '组合拼写错误次数',
  `composite_spell_right_num` int(11) NOT NULL DEFAULT '0' COMMENT '组合拼写正确次数',
  `whole_spell_wrong_num` int(10) NOT NULL DEFAULT '0' COMMENT '全部拼写错误次数',
  `whole_spell_right_num` int(11) NOT NULL DEFAULT '0' COMMENT '全部拼写正确次数',
  `device_id` varchar(32) NOT NULL DEFAULT '' COMMENT '设备id',
  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '具体地址',
  `longitude` varchar(16) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(16) NOT NULL DEFAULT '' COMMENT '纬度',
  `duration` int(10) NOT NULL DEFAULT '0' COMMENT '识记时长(毫秒)',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记开始时间',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '识记结束时间',
  `know_duration` int(10) NOT NULL DEFAULT '0',
  `current_start_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `click_group_no` int(10) NOT NULL DEFAULT '0' COMMENT '点读组号',
  `is_given` tinyint(4) NOT NULL DEFAULT '0' COMMENT '该单词是被用来计算学分学币：0-没用过；1-用过；2-不参与计算',
  `click_num` int(10) NOT NULL DEFAULT '0' COMMENT '点击次数',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `student_unit_id` (`student_unit_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='学生速记单词表';

CREATE TABLE `vocabulary_test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0',
  `store_id` int(10) NOT NULL DEFAULT '0',
  `agent_id` int(10) NOT NULL DEFAULT '0',
  `read_quantity` int(10) NOT NULL DEFAULT '0',
  `listen_quantity` int(10) NOT NULL DEFAULT '0',
  `en_level` varchar(10) NOT NULL DEFAULT '',
  `ch_level` varchar(30) DEFAULT '',
  `grade_level` varchar(50) DEFAULT '',
  `score` varchar(100) NOT NULL DEFAULT '',
  `sub_score` varchar(150) NOT NULL DEFAULT '',
  `unknow_num` int(10) NOT NULL DEFAULT '0',
  `unanswer_num` int(10) NOT NULL DEFAULT '0',
  `wrong_num` int(10) NOT NULL DEFAULT '0',
  `right_num` int(10) NOT NULL DEFAULT '0',
  `total_num` int(10) NOT NULL DEFAULT '0',
  `duration` int(10) NOT NULL DEFAULT '0',
  `start_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `type` tinyint(4) NOT NULL DEFAULT '0',
  `vocabulary_result` text NOT NULL,
  `address` varchar(200) NOT NULL DEFAULT '',
  `longitude` varchar(16) NOT NULL DEFAULT '',
  `latitude` varchar(16) NOT NULL DEFAULT '',
  `memory_result` varchar(200) NOT NULL DEFAULT '',
  `attention_result` varchar(200) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `student_id` (`student_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vocabulary_test_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(10) NOT NULL DEFAULT '0',
  `vocabulary_test_id` int(10) NOT NULL,
  `word` varchar(200) NOT NULL DEFAULT '',
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `duration` int(10) NOT NULL DEFAULT '0',
  `type` int(10) NOT NULL DEFAULT '0',
  `vocabulary_text` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `student_id` (`student_id`),
  KEY `vocabulary_test_id` (`vocabulary_test_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '英文',
  `phonetic_am` varchar(100) NOT NULL DEFAULT '' COMMENT '音标:美',
  `phonetic_en` varchar(100) NOT NULL DEFAULT '' COMMENT '音标:英',
  `syllable` varchar(100) NOT NULL DEFAULT '' COMMENT '音节划分',
  `split` varchar(100) NOT NULL DEFAULT '' COMMENT '单词划分',
  `common_mean` varchar(100) NOT NULL DEFAULT '' COMMENT '常见词意',
  `common_mean_pos` varchar(100) NOT NULL DEFAULT '' COMMENT '常见词意带词性',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词状态；1-待审核；2-已通过；3-已删除',
  `attribute` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词属性：1-单词；2-词组',
  `requirement_stage1` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1-小学考纲要求拼写 0-不要求',
  `requirement_stage2` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1-初中考纲要求拼写 0-不要求',
  `requirement_stage3` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1-高中考纲要求拼写;0-不要求',
  `en_voice_url` varchar(255) NOT NULL DEFAULT '' COMMENT '英音发音地址',
  `en_updated_at` datetime NOT NULL COMMENT '英音资源最后更新时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `confuse_split` varchar(100) NOT NULL DEFAULT '' COMMENT '拆分混淆项',
  `hint` varchar(100) NOT NULL DEFAULT '' COMMENT '客户端提示',
  `mnemonic_id` int(10) NOT NULL DEFAULT '0' COMMENT '默认助记id',
  `syllable_bak` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `word` (`word`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础词表';

CREATE TABLE `word_error` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(20) NOT NULL DEFAULT '',
  `student_id` int(10) NOT NULL DEFAULT '0' COMMENT '纠错人',
  `device_id` varchar(32) NOT NULL DEFAULT '',
  `student_wordset_id` int(11) NOT NULL DEFAULT '0',
  `wordset_id` int(11) NOT NULL DEFAULT '0',
  `word` varchar(50) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL,
  `detail` text NOT NULL,
  `resource_version` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `source` tinyint(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='单词纠错表';

CREATE TABLE `word_meaning` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `pos` varchar(50) NOT NULL DEFAULT '' COMMENT 'part of speech词性',
  `meaning` varchar(200) NOT NULL DEFAULT '' COMMENT '词义',
  `level` tinyint(4) NOT NULL DEFAULT '1' COMMENT '级别：1-小学；2-初中；3-高中；4-大学；5-大学以上',
  `sentence_ids` varchar(200) NOT NULL DEFAULT '' COMMENT '例句id，多个用英文逗号分隔',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词词义状态；1-待审核；2-已通过；3-已删除',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  PRIMARY KEY (`id`),
  KEY `word_id` (`word_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='单词词义表';

CREATE TABLE `word_mnemonic` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '单词id',
  `mnemonic_id` int(10) NOT NULL DEFAULT '0' COMMENT '助记id',
  `priority` int(10) NOT NULL DEFAULT '0' COMMENT '优先级，数值越大，优先级越高',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `updated_by` varchar(20) NOT NULL DEFAULT '' COMMENT '最后修改者',
  PRIMARY KEY (`id`),
  KEY `word_id` (`word_id`) USING BTREE,
  KEY `mnemonic_id` (`mnemonic_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='英语单词助记对应表';

CREATE TABLE `wordset` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) NOT NULL DEFAULT '' COMMENT '名称',
  `category` tinyint(4) NOT NULL DEFAULT '1' COMMENT '类型：1-普通词库；2-课本词库',
  `material` varchar(40) NOT NULL DEFAULT '' COMMENT '教材版本',
  `no` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '词库排序号',
  `stage` tinyint(4) NOT NULL DEFAULT '1' COMMENT '学段：1-小学；2-初中；3-高中；4-大学；5-大学以上',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词状态；1-待审核；2-已通过；3-已删除',
  `level` int(10) NOT NULL DEFAULT '0' COMMENT '''词库等级：1000,1001,2002,2003第一个1代表学段，第二位代表年级，后三位数字代表在这个学段中的等级'',',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '总单词数',
  `unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '单元总数',
  `unit_name` text NOT NULL,
  `children_no` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '子词库排序号',
  `type` tinyint(4) NOT NULL DEFAULT '1',
  `remark` varchar(100) NOT NULL DEFAULT '' COMMENT '修改词库备注',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='词库表';

CREATE TABLE `wordset_201806062028` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) NOT NULL DEFAULT '' COMMENT '名称',
  `category` tinyint(4) NOT NULL DEFAULT '1' COMMENT '类型：1-普通词库；2-课本词库',
  `material` varchar(40) NOT NULL DEFAULT '' COMMENT '教材版本',
  `no` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '词库排序号',
  `stage` tinyint(4) NOT NULL DEFAULT '1' COMMENT '学段：1-小学；2-初中；3-高中；4-大学；5-大学以上',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词状态；1-待审核；2-已通过；3-已删除',
  `level` int(10) NOT NULL DEFAULT '0' COMMENT '''词库等级：1000,1001,2002,2003第一个1代表学段，第二位代表年级，后三位数字代表在这个学段中的等级'',',
  `total_word_num` int(10) NOT NULL DEFAULT '0' COMMENT '总单词数',
  `unit_num` int(10) NOT NULL DEFAULT '0' COMMENT '单元总数',
  `children_no` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '子词库排序号',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='词库表';

CREATE TABLE `wordset_word` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word_id` int(10) NOT NULL DEFAULT '0' COMMENT '基础词表id',
  `word_meaning_ids` varchar(20) NOT NULL DEFAULT '' COMMENT '词义id',
  `word_meaning` varchar(500) NOT NULL DEFAULT '' COMMENT '单词用'';''分割,去重',
  `word_meaning_pos` varchar(500) NOT NULL DEFAULT '' COMMENT '不同类别用''|''分割（展示时替换成'';''), 不同词性 用'';''分割,同类(词性）内用'',''分割',
  `wordset_id` int(10) NOT NULL DEFAULT '0' COMMENT '词库id',
  `mnemonic_id` int(10) NOT NULL DEFAULT '0' COMMENT '助记表id',
  `unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '单元序号',
  `old_unit_no` int(10) NOT NULL DEFAULT '0' COMMENT '拆单元前的单元号',
  `group_no` int(10) NOT NULL DEFAULT '1' COMMENT '单词在本单元中的分组',
  `no` int(10) NOT NULL DEFAULT '0' COMMENT '排序序号',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '单词状态；1-待审核；2-已通过；3-已删除;',
  `remark` varchar(100) NOT NULL DEFAULT '' COMMENT '修改词库备注',
  `requirement` varchar(50) NOT NULL DEFAULT '' COMMENT '考纲要求：1-写作高频词；2-要求拼写；3-不要求拼写；4-超纲（高考）；5-听力，以逗号分隔',
  `syllable` varchar(100) NOT NULL DEFAULT '' COMMENT '音节划分',
  `hint` varchar(100) NOT NULL DEFAULT '' COMMENT '客户端提示',
  `split` varchar(100) NOT NULL DEFAULT '' COMMENT '单词划分',
  `confuse_split` varchar(100) NOT NULL DEFAULT '' COMMENT '单词划分',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(32) NOT NULL DEFAULT '' COMMENT '更新者',
  `syllable_bak` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `unique` (`word_id`,`wordset_id`,`unit_no`) USING BTREE,
  KEY `wordset_id` (`wordset_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='词库单词表';

