// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: my.proto

// 此处定义了生成的xxxx.pb.go中的package名字

package my

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyRequest_Color int32

const (
	MyRequest_WHITE MyRequest_Color = 0
	MyRequest_RED   MyRequest_Color = 1
	MyRequest_BLUE  MyRequest_Color = 2
	MyRequest_GREEN MyRequest_Color = 3
)

// Enum value maps for MyRequest_Color.
var (
	MyRequest_Color_name = map[int32]string{
		0: "WHITE",
		1: "RED",
		2: "BLUE",
		3: "GREEN",
	}
	MyRequest_Color_value = map[string]int32{
		"WHITE": 0,
		"RED":   1,
		"BLUE":  2,
		"GREEN": 3,
	}
)

func (x MyRequest_Color) Enum() *MyRequest_Color {
	p := new(MyRequest_Color)
	*p = x
	return p
}

func (x MyRequest_Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyRequest_Color) Descriptor() protoreflect.EnumDescriptor {
	return file_my_proto_enumTypes[0].Descriptor()
}

func (MyRequest_Color) Type() protoreflect.EnumType {
	return &file_my_proto_enumTypes[0]
}

func (x MyRequest_Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyRequest_Color.Descriptor instead.
func (MyRequest_Color) EnumDescriptor() ([]byte, []int) {
	return file_my_proto_rawDescGZIP(), []int{0, 0}
}

// message 推荐大写
type MyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号从1开始
	Name  string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // 消息字段名推荐小写
	Id    int64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                               // 消息字段名推荐小写
	Color MyRequest_Color `protobuf:"varint,4,opt,name=color,proto3,enum=my.MyRequest_Color" json:"color,omitempty"` // 枚举字段
}

func (x *MyRequest) Reset() {
	*x = MyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRequest) ProtoMessage() {}

func (x *MyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_my_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRequest.ProtoReflect.Descriptor instead.
func (*MyRequest) Descriptor() ([]byte, []int) {
	return file_my_proto_rawDescGZIP(), []int{0}
}

func (x *MyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MyRequest) GetColor() MyRequest_Color {
	if x != nil {
		return x.Color
	}
	return MyRequest_WHITE
}

type MyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *MyRequest `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *MyResponse) Reset() {
	*x = MyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyResponse) ProtoMessage() {}

func (x *MyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_my_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyResponse.ProtoReflect.Descriptor instead.
func (*MyResponse) Descriptor() ([]byte, []int) {
	return file_my_proto_rawDescGZIP(), []int{1}
}

func (x *MyResponse) GetRes() *MyRequest {
	if x != nil {
		return x.Res
	}
	return nil
}

var File_my_proto protoreflect.FileDescriptor

var file_my_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6d, 0x79, 0x22, 0x8c,
	0x01, 0x0a, 0x09, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x6d, 0x79, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x05, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x48, 0x49, 0x54, 0x45, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4c, 0x55, 0x45,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x45, 0x45, 0x4e, 0x10, 0x03, 0x22, 0x2d, 0x0a,
	0x0a, 0x4d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x79, 0x2e, 0x4d, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x36, 0x0a, 0x0c,
	0x4d, 0x79, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x05,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x12, 0x0d, 0x2e, 0x6d, 0x79, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x79, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_my_proto_rawDescOnce sync.Once
	file_my_proto_rawDescData = file_my_proto_rawDesc
)

func file_my_proto_rawDescGZIP() []byte {
	file_my_proto_rawDescOnce.Do(func() {
		file_my_proto_rawDescData = protoimpl.X.CompressGZIP(file_my_proto_rawDescData)
	})
	return file_my_proto_rawDescData
}

var file_my_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_my_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_my_proto_goTypes = []interface{}{
	(MyRequest_Color)(0), // 0: my.MyRequest.Color
	(*MyRequest)(nil),    // 1: my.MyRequest
	(*MyResponse)(nil),   // 2: my.MyResponse
}
var file_my_proto_depIdxs = []int32{
	0, // 0: my.MyRequest.color:type_name -> my.MyRequest.Color
	1, // 1: my.MyResponse.res:type_name -> my.MyRequest
	1, // 2: my.MyRPCService.GetMy:input_type -> my.MyRequest
	2, // 3: my.MyRPCService.GetMy:output_type -> my.MyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_my_proto_init() }
func file_my_proto_init() {
	if File_my_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_my_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_my_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_my_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_my_proto_goTypes,
		DependencyIndexes: file_my_proto_depIdxs,
		EnumInfos:         file_my_proto_enumTypes,
		MessageInfos:      file_my_proto_msgTypes,
	}.Build()
	File_my_proto = out.File
	file_my_proto_rawDesc = nil
	file_my_proto_goTypes = nil
	file_my_proto_depIdxs = nil
}
