// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserByServerStream(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (UserService_GetUserByServerStreamClient, error)
	GetUserByClientStream(ctx context.Context, opts ...grpc.CallOption) (UserService_GetUserByClientStreamClient, error)
	GetUserByStream(ctx context.Context, opts ...grpc.CallOption) (UserService_GetUserByStreamClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByServerStream(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (UserService_GetUserByServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/user.UserService/GetUserByServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetUserByServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_GetUserByServerStreamClient interface {
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceGetUserByServerStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceGetUserByServerStreamClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) GetUserByClientStream(ctx context.Context, opts ...grpc.CallOption) (UserService_GetUserByClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/user.UserService/GetUserByClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetUserByClientStreamClient{stream}
	return x, nil
}

type UserService_GetUserByClientStreamClient interface {
	Send(*UserRequest) error
	CloseAndRecv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceGetUserByClientStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceGetUserByClientStreamClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceGetUserByClientStreamClient) CloseAndRecv() (*UserResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) GetUserByStream(ctx context.Context, opts ...grpc.CallOption) (UserService_GetUserByStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[2], "/user.UserService/GetUserByStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetUserByStreamClient{stream}
	return x, nil
}

type UserService_GetUserByStreamClient interface {
	Send(*UserRequest) error
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceGetUserByStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceGetUserByStreamClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceGetUserByStreamClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUserByServerStream(*UserRequest, UserService_GetUserByServerStreamServer) error
	GetUserByClientStream(UserService_GetUserByClientStreamServer) error
	GetUserByStream(UserService_GetUserByStreamServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUserByServerStream(*UserRequest, UserService_GetUserByServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserByServerStream not implemented")
}
func (UnimplementedUserServiceServer) GetUserByClientStream(UserService_GetUserByClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserByClientStream not implemented")
}
func (UnimplementedUserServiceServer) GetUserByStream(UserService_GetUserByStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserByStream not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserByServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetUserByServerStream(m, &userServiceGetUserByServerStreamServer{stream})
}

type UserService_GetUserByServerStreamServer interface {
	Send(*UserResponse) error
	grpc.ServerStream
}

type userServiceGetUserByServerStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceGetUserByServerStreamServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_GetUserByClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).GetUserByClientStream(&userServiceGetUserByClientStreamServer{stream})
}

type UserService_GetUserByClientStreamServer interface {
	SendAndClose(*UserResponse) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type userServiceGetUserByClientStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceGetUserByClientStreamServer) SendAndClose(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceGetUserByClientStreamServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserService_GetUserByStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).GetUserByStream(&userServiceGetUserByStreamServer{stream})
}

type UserService_GetUserByStreamServer interface {
	Send(*UserResponse) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type userServiceGetUserByStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceGetUserByStreamServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceGetUserByStreamServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserByServerStream",
			Handler:       _UserService_GetUserByServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserByClientStream",
			Handler:       _UserService_GetUserByClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetUserByStream",
			Handler:       _UserService_GetUserByStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "user-server-stream.proto",
}
